Updated Overview Label Tooltip Language
privacy-tech-lab/privacy-pioneer pull request #515
Opened 2023-06-21 15:22 UTC by jjeancharles

Closes #508

2023-06-21 19:41 UTC, danielgoldelman requested changes
I think it should be "collected or received"

2023-06-27 15:23 UTC, jjeancharles commented
@danielgoldelman Applied changes in new commit

2023-06-27 17:11 UTC, SebastianZimmeck approved these changes

2023-06-27 17:11 UTC, SebastianZimmeck commented
This works for me (including @danielgoldelman's change suggestions).

2023-06-28 22:47 UTC, merged